### ISSUE TITLE
Upgrade from 3.2 -> 3.3 - service-signer.crt file does not exist

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#110]
The above error is blocking an upgrade from 3.2 to 3.3.

From the master-config.yaml template:

```
<% if @ose_major_version.split('.')[1].to_i.between?(3,4) %>                                                                                                                                               
controllerConfig:                                                                                                                                                                                          
  serviceServingCert:                                                                                                                                                                                      
    signer:                                                                                                                                                                                                
      certFile: service-signer.crt                                                                                                                                                                         
      keyFile: service-signer.key                                                                                                                                                                          
<%- end -%>                 
```

Looks like the ansible one handles this:

https://github.com/openshift/openshift-ansible/pull/2449/files

I can either handle this 'by hand' in our upgrade chef scripts, or we can add the upgrade capability within the community scripts (and automate tests etc)

@IshentRas  what do you think?
