### ISSUE TITLE
Bug: between 1.10.35 and 1.10.44, ldap error

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#115]
old snip:

```
  identityProviders:
  - name: ldap_identity
    challenge: true
    login: true
    provider:
      apiVersion: v1
      kind: BasicAuthPasswordIdentityProvider
      url: https://auth-service-openshift-infra.appcloud-pilot.barcapint.com/auth/ldap_auth
  masterPublicURL: 
```

new snip:

```
  - name: ldap_identity
    challenge: true
    login: true
    provider:
      apiVersion: v1
      kind: BasicAuthPasswordIdentityProvider
      url: https://auth-service-openshift-infra.appcloud-pilot.barcapint.com/auth/ldap_auth
        ca:
        certFile:
        keyFile:
  masterPublicURL: 
```

error: 

```
Apr 25 16:26:19 gdcdsr000002532.intranet.barcapint.com atomic-openshift-master-api[102923]: F0425 16:26:19.721911  102923 start_api.go:65] could not load config file "/etc/origin/master/master-config.yaml" due to an error: yaml: line 105: mapping values are not allowed in this context
```
